version: '3.8'

services:
  # Redis for message queuing and caching
  redis:
    image: redis:7-alpine
    container_name: rfid-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Supabase Local Development
  supabase-db:
    image: supabase/postgres:15.1.0.117
    container_name: rfid-supabase-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
      - ./supabase/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Supabase Studio
  supabase-studio:
    image: supabase/studio:20231215-4b8b8b8
    container_name: rfid-supabase-studio
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://supabase-meta:8080
      POSTGRES_PASSWORD: postgres
      DEFAULT_ORGANIZATION_NAME: RFID Platform
      DEFAULT_PROJECT_NAME: Local Development
    depends_on:
      - supabase-db

  # Supabase Meta
  supabase-meta:
    image: supabase/postgres-meta:v0.68.0
    container_name: rfid-supabase-meta
    ports:
      - "8080:8080"
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: postgres
      PG_META_DB_PASSWORD: postgres
    depends_on:
      - supabase-db

  # API Gateway
  gateway:
    build:
      context: ../../apps/gateway
      dockerfile: ../../infra/docker/Dockerfile.gateway
    container_name: rfid-gateway
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - SECRET_KEY=dev-secret-key-change-in-production
      - SUPABASE_URL=http://supabase-db:5432
      - SUPABASE_SERVICE_KEY=dev-service-key
      - REDIS_URL=redis://redis:6379
      - RATE_LIMITING_ENABLED=true
      - TELEMETRY_ENABLED=false
    depends_on:
      redis:
        condition: service_healthy
      supabase-db:
        condition: service_healthy
    volumes:
      - ../../apps/gateway:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Ingest Worker
  worker:
    build:
      context: ../../apps/ingest-worker
      dockerfile: ../../infra/docker/Dockerfile.worker
    container_name: rfid-worker
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - SUPABASE_URL=http://supabase-db:5432
      - SUPABASE_SERVICE_KEY=dev-service-key
      - REDIS_URL=redis://redis:6379
      - WORKER_ID=worker-1
      - BATCH_SIZE=100
      - TELEMETRY_ENABLED=false
    depends_on:
      redis:
        condition: service_healthy
      supabase-db:
        condition: service_healthy
    volumes:
      - ../../apps/ingest-worker:/app
    command: python main.py

  # Dashboard (Development)
  dashboard:
    build:
      context: ../../apps/dashboard
      dockerfile: ../../infra/docker/Dockerfile.dashboard
    container_name: rfid-dashboard
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:5432
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=dev-anon-key
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - gateway
    volumes:
      - ../../apps/dashboard:/app
      - /app/node_modules
    command: npm run dev

  # Mobile App (Development)
  mobile:
    build:
      context: ../../apps/mobile
      dockerfile: ../../infra/docker/Dockerfile.mobile
    container_name: rfid-mobile
    ports:
      - "3002:3001"
    environment:
      - VITE_SUPABASE_URL=http://localhost:5432
      - VITE_SUPABASE_ANON_KEY=dev-anon-key
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - gateway
    volumes:
      - ../../apps/mobile:/app
      - /app/node_modules
    command: npm run dev

volumes:
  redis_data:
  supabase_data:

networks:
  default:
    name: rfid-platform
