name: CI - compiler
on: [push, pull_request]
jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: weft/compiler
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --verbose
      - run: |
          if ls **/*_test.rs >/dev/null 2>&1 || grep -R "mod tests" -n compiler/src >/dev/null 2>&1; then
            cargo test --verbose
          else
            echo "No Rust tests detected; skipping cargo test"
          fi
